# Generated by Django 5.1.3 on 2025-02-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.IntegerField(default=5),
        ),
    ]
